FROM aiblocks/base:latest

MAINTAINER AiBlocks Dev <dev@aiblocks.io>

EXPOSE 11625
EXPOSE 11626

VOLUME /data
VOLUME /heka

ADD aiblocks-core.deb /
ADD install /
RUN /install

ADD heka /heka
ADD confd /etc/confd
ADD utils /utils
ADD start /

CMD ["/start"]
